# Generated by Django 3.2.7 on 2022-01-27 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualzado_en', models.DateTimeField(auto_now=True)),
                ('id_course', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=500)),
                ('estimated_content_length', models.IntegerField()),
                ('has_closed_caption', models.BooleanField()),
                ('last_update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhatYouWillLearnModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualzado_en', models.DateTimeField(auto_now=True)),
                ('id_what_you_will_learn', models.IntegerField()),
                ('what_you_will_learn', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CourseHasWhatYouWillLearn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.coursemodel')),
                ('what_you_will_learn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.whatyouwilllearnmodel')),
            ],
        ),
    ]
