# Generated by Django 3.2.12 on 2022-02-09 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0002_alter_coursemodel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='id_course',
            field=models.IntegerField(unique=True),
        ),
    ]
