# Generated by Django 4.0.1 on 2022-01-28 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0003_remove_coursemodel_last_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatyouwilllearnmodel',
            name='id_what_you_will_learn',
        ),
    ]
