# Generated by Django 3.2.12 on 2022-02-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0003_alter_coursemodel_id_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='empresa',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='keyword',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
