# Generated by Django 4.0.1 on 2022-01-28 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0004_remove_whatyouwilllearnmodel_id_what_you_will_learn'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptionLanguagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualzado_en', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualzado_en', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='InstructorsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualzado_en', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LocalesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualzado_en', models.DateTimeField(auto_now=True)),
                ('locale_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryCategoriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualzado_en', models.DateTimeField(auto_now=True)),
                ('primary_category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RequiredEducationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualzado_en', models.DateTimeField(auto_now=True)),
                ('required_education', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RequirementsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualzado_en', models.DateTimeField(auto_now=True)),
                ('requirements', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CourseHasRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.coursemodel')),
                ('requirements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.requirementsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CourseHasRequiredEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.coursemodel')),
                ('required_education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.requirededucationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CourseHasPrimaryCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.coursemodel')),
                ('primary_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.primarycategoriesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CourseHasLocales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.coursemodel')),
                ('locale_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.localesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CourseHasInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.coursemodel')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.instructorsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CourseHasCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.categoriesmodel')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.coursemodel')),
            ],
        ),
        migrations.CreateModel(
            name='CourseHasCaptionLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.coursemodel')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.captionlanguagesmodel')),
            ],
        ),
    ]
