# Generated by Django 4.0.1 on 2022-01-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0005_captionlanguagesmodel_categoriesmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course2Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualzado_en', models.DateTimeField(auto_now=True)),
                ('id_course', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=500)),
                ('estimated_content_length', models.IntegerField()),
                ('has_closed_caption', models.BooleanField()),
                ('what_you_will_learn', models.CharField(max_length=2000)),
                ('language', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('requirements', models.CharField(max_length=200)),
                ('locale_description', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('primary_category', models.CharField(max_length=200)),
                ('required_education', models.CharField(max_length=200)),
            ],
        ),
    ]
