# Generated by Django 4.0.1 on 2022-01-31 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0006_course2model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course2model',
            name='id',
        ),
        migrations.AlterField(
            model_name='course2model',
            name='id_course',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
