# Generated by Django 3.2.12 on 2022-05-17 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0008_reader'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
