name: Master
on:
  push:
    branches:
      - master
  schedule:
    - cron: '5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Checkout repository content
      uses: actions/checkout@v2 # Checkout the repository content to github runner.

    - name: Setup Python Version
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 # Install the python version needed

    - name: Execute Python script # Run the app.py
      run: python ./Thincrs_EduacionApp/Cursos/send_email.py